# Generated by Django 5.1.5 on 2025-01-21 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_remove_contact_email_remove_contact_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='username',
            new_name='user',
        ),
    ]
